### ISSUE TITLE
could you make a flatpak for wallpaperize?

### ISSUE THREAD

**Issue by ghost** [Philip-Scott/wallpaperize#16]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for wallpaperize?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by Philip-Scott** [comment]
Hey! To be honest, while i would love to bring the app to other Linux distributions, i sadly don't have the time to maintain these apps on every distribution. Both Notes-Up, and Wallpaperize are made for and on  elementary OS, which makes things easier on my side since i can test them while i use them daily, which is not the case whenever it's packaged for other distros.

That said, if the community builds and maintains Flatpaks (Like it's been done with Spice-Up and Notes-Up) then for all means it's fine by me :) But any issues that could be presented from the external packaging would also requite community help.

A .deb for Wallpaperise is also available over at: http://packages.elementary.io/appcenter/pool/main/c/com.github.philip-scott.wallpaperize/

_I'll be closing and marking this issue as "Out of Scope" :)_

**Comment by ghost** [comment]
i see , i understand the situation.
maybe the community , could build and maintenance those applications to flatpak format in the future
thanks for the explication.
